links:
  scholar: https://scholar.google.com/citations?user=qlRTEOYAAAAJ&hl=en
  researchgate: https://www.researchgate.net/profile/Bahetihazi-Maidu
  github: https://github.com/bmaidu
  linkedin: https://www.linkedin.com/in/bahetihazi-maidu-6578b92bb
